// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCReaqjJVy4YgtdqJUYl0zPDpokiJabp4',
    appId: '1:110693461898:web:7128e534a1142f8c8b6273',
    messagingSenderId: '110693461898',
    projectId: 'reservasapp-7a549',
    authDomain: 'reservasapp-7a549.firebaseapp.com',
    storageBucket: 'reservasapp-7a549.appspot.com',
    measurementId: 'G-J9GW2TGW1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0z6k3mRksfbkPPX-4vuryzF3Dq6Vy3uU',
    appId: '1:110693461898:android:253052276156f47b8b6273',
    messagingSenderId: '110693461898',
    projectId: 'reservasapp-7a549',
    storageBucket: 'reservasapp-7a549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIHNgF6hoeIVZEHCdNP0wrXwogYX1_3PY',
    appId: '1:110693461898:ios:a71ce5471ff84d5a8b6273',
    messagingSenderId: '110693461898',
    projectId: 'reservasapp-7a549',
    storageBucket: 'reservasapp-7a549.appspot.com',
    iosBundleId: 'com.example.reservasApp',
  );
}
